version: '3'

services:
  mongodb:
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=test
      - MONGO_INITDB_ROOT_USERNAME=$USER
      - MONGO_INITDB_ROOT_PASSWORD=$PASSWD
    ports:
      - "27017:27017"
    command: mongod --auth
    volumes:
      - ~/apps/mongo:/data/db

  app:
    build: .
    command: bash -c "uvicorn main:app --host 0.0.0.0 --port 8080"
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    links:
      - mongodb
    depends_on: [mongodb]


